from __future__ import annotations


REBIRTH_SCORE = 10_000
DEATH_SCORE = 9_000
EAT_CORPSE_SCORE = 800
EAT_FOOD_BASE_SCORE = 500
AVOID_HAZARD_BASE_SCORE = 300
REACT_CORPSE_SCORE = 250
SEED_DAILY_HAZARD_SCORE = 180
GIVE_GIFT_BASE_SCORE = 120
GIVE_GIFT_AFFECTION_WEIGHT = 5
ROAM_BASE_SCORE = 70
VOCALIZE_SCORE = 10

ROOM_FAMILIARITY_WEIGHT = 5
ROOM_GIFT_WEIGHT = 12
ROOM_FOOD_MEMORY_WEIGHT = 18
ROOM_QUIET_WEIGHT = 8
ROOM_CURIOUS_TAG_WEIGHT = 6
ROOM_EXPOSED_PENALTY = 10
ROOM_CORPSE_PENALTY = 80
ROOM_HAZARD_PENALTY = 120
ROOM_FEAR_PENALTY = 1
ROOM_CURIOSITY_WEIGHT = 1
